name: check Torizon core builder updates

on:
  workflow_call:
    inputs:
        manufacturer:
          required: true
          type: string
    secrets:
        auto_update_token:
          required: true

jobs:
    check-torizon-core-builder-updates:
    name: Check for Torizon core builder updates
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout torizon-optologic
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          ref: 'torizon-${{ inputs.manufacturer }}-7.x.y'

      - name: Check for torizon core builder updates
        id: check-for-torizon-core-builder-updates
        run: |
            set +e
            .github/scripts/check-torizon-core-builder-updates.sh
            exit_code="$?"
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            if [[ $exit_code -eq 1 ]]; then
                exit 1
            fi

      - name: Check for closed pull request on the torizon-core-builder-${{ inputs.manufacturer }}-update/${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}} branch
        if: steps.check-for-torizon-core-builder-updates.outputs.exit_code == '2'
        id: find-torizon-core-builder-pull-request
        uses: juliangruber/find-pull-request-action@v1
        with:
            state: closed
            branch: torizon-core-builder-${{ inputs.manufacturer }}-update/${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}}

      - name: Open a pull request with the updated BSP
        if: steps.check-for-torizon-core-builder-updates.outputs.exit_code == '2' && steps.find-torizon-core-builder-pull-request.outputs.matching-pr-count == 0
        id: cpr-core-builder
        uses: peter-evans/create-pull-request@v8
        with:
            token: ${{ secrets.auto_update_token }}
            commit-message: ".github:workflows: update to Torizon core builder ${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}} version"
            title: "${{ inputs.manufacturer }}: Update Torizon core builder to the ${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}} version"
            body: This pull request updates the Torizon core builder to the ${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}} version.
            branch: toradex-${{ inputs.manufacturer }}-manifest-update/${{steps.check-for-torizon-core-builder-updates.outputs.latest_stable_tag}}
            signoff: true

      - name: Output pull request details
        if: ${{ steps.cpr-core-builder.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr-core-builder.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr-core-builder.outputs.pull-request-url }}"
